# Generated by Django 3.2.16 on 2023-01-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('saint_name', models.CharField(max_length=30, verbose_name='Tên thánh')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='pics', verbose_name='Hình đại diện')),
                ('facebook', models.CharField(default='', max_length=400, verbose_name='Link facebook')),
                ('address', models.CharField(default='', max_length=300, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Số điện thoại')),
                ('last_update_time', models.DateField(auto_now=True, null=True, verbose_name='Lần cuối truy cập')),
                ('account_confimred', models.BooleanField(blank=True, default=False, null=True, verbose_name='Xác minh')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Mã xác nhận')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'User profile',
                'ordering': ('user__username', 'user__email'),
                'unique_together': {('user', 'full_name', 'address')},
            },
        ),
    ]
