# Generated by Django 3.2.16 on 2023-01-03 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230103_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='userId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
