# Generated by Django 3.2.16 on 2023-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230107_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/users', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='saint_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Tên thánh'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
