# Generated by Django 3.2.16 on 2023-01-14 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0011_auto_20230111_1710'),
        ('home', '0012_auto_20230112_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_type_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('language', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_language', to='kanri.language', verbose_name='Ngon ngu')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_type_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Bài hoc-phân loại',
                'verbose_name_plural': 'Bài hoc-phân loại',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonChapterQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.SmallIntegerField(default=0, verbose_name='Câu hỏi số')),
                ('question', models.TextField(max_length=500, verbose_name='Câu hỏi')),
                ('answer', models.TextField(max_length=1000, verbose_name='Câu trả lời')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessonchapter', verbose_name='Bài')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessontype', verbose_name='Phan loại'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
