# Generated by Django 3.2.16 on 2023-01-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên Nhà thờ', max_length=120, verbose_name='Tên Nhà thờ')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh đại diện', null=True, upload_to='images', verbose_name='Hình ảnh')),
                ('introduction', tinymce.models.HTMLField(blank=True, help_text='Mô tả sơ lược về Nhà thờ', verbose_name='Giới thiệu')),
                ('url', models.CharField(blank=True, default='', help_text='Link liên kết', max_length=100, verbose_name='Web URL')),
                ('phone', models.CharField(blank=True, default='', help_text='Số điện thoại', max_length=15, verbose_name='Điện thoại')),
                ('email', models.CharField(blank=True, default='', help_text='Địa chỉ email', max_length=50, verbose_name='Email')),
                ('language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='jp', max_length=50, verbose_name='Ngôn ngữ')),
                ('language1', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ phụ')),
                ('address', models.CharField(help_text='Địa chỉ', max_length=400, verbose_name='Địa chỉ')),
                ('google_map_link', models.CharField(max_length=500, verbose_name='googlemap link')),
                ('notice_on_map', tinymce.models.HTMLField(blank=True, default='', help_text='Nội dung hiển thị trên Map', verbose_name='Thông báo')),
                ('geo_lon', models.FloatField(blank=True, default=0.0, help_text='Kinh độ theo bản đồ Google', null=True, verbose_name='Kinh độ')),
                ('geo_lat', models.FloatField(blank=True, default=0.0, help_text='Vĩ độ theo bản đồ Google', null=True, verbose_name='Vĩ độ')),
                ('geo_hash', models.CharField(blank=True, default='', max_length=30, verbose_name='geo_hash')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Nhà thờ',
                'verbose_name_plural': 'Nhà thờ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_name', models.CharField(max_length=50, verbose_name='Tên tiếng Nhật')),
                ('english_name', models.CharField(max_length=50, verbose_name='Tên theo tiếng Anh')),
                ('vietnamese_name', models.CharField(max_length=50, verbose_name='Tên theo tiếng Việt')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Đất nước',
                'verbose_name_plural': 'Đất nước',
                'ordering': ('english_name',),
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên Nhà thờ', max_length=200, verbose_name='Tên Nhà thờ')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh đại diện', null=True, upload_to='images', verbose_name='Hình ảnh')),
                ('introduction', tinymce.models.HTMLField(blank=True, help_text='Mô tả sơ lược về Nhà thờ', verbose_name='Giới thiệu')),
                ('url', models.CharField(blank=True, default='', help_text='Link liên kết', max_length=100, verbose_name='Web URL')),
                ('phone', models.CharField(blank=True, default='', help_text='Số điện thoại', max_length=15, verbose_name='Điện thoại')),
                ('email', models.CharField(blank=True, default='', help_text='Địa chỉ email', max_length=50, verbose_name='Email')),
                ('address', models.CharField(help_text='Địa chỉ', max_length=255, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà thờ',
                'verbose_name_plural': 'Nhà thờ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('saint_name', models.CharField(max_length=30, verbose_name='Tên thánh')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('introduction', tinymce.models.HTMLField(verbose_name='Giới thiệu')),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='images/fathers', verbose_name='Hình đại diện')),
                ('facebook', models.CharField(default='', max_length=400, verbose_name='Link facebook')),
                ('address', models.CharField(default='', max_length=300, verbose_name='Địa chỉ hiện tại')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Số điện thoại')),
                ('last_update_time', models.DateField(auto_now=True, null=True, verbose_name='Lần cuối truy cập')),
                ('account_confimred', models.BooleanField(blank=True, default=False, null=True, verbose_name='Xác minh')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.facility', verbose_name='Tên nơi thuộc về')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Quý cha',
                'verbose_name_plural': 'Quý cha',
                'ordering': ('full_name', 'user__username', 'user__email'),
                'unique_together': {('user', 'full_name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(help_text='Ngôn ngữ của Quốc gia', max_length=50, verbose_name='Tên Ngôn ngữ')),
                ('language_code', models.CharField(help_text='Mã theo i18n', max_length=3, verbose_name='Mã')),
                ('language_en_name', models.CharField(help_text='Tên theo tiếng anh', max_length=50, verbose_name='Tên quốc tế')),
                ('language_flag_small_url', models.ImageField(blank=True, help_text='Hình ảnh minh hoạ', null=True, upload_to='flags', verbose_name='Hình ảnh')),
                ('language_flag_medium_url', models.ImageField(blank=True, help_text='Hình ảnh minh hoạ', null=True, upload_to='flags', verbose_name='Hình ảnh')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('hiragana', models.CharField(max_length=50, verbose_name='Tên tiếng nhật')),
                ('name', models.CharField(max_length=50, verbose_name='Tên theo tiếng anh')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Mã')),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kanri.country', verbose_name='Quốc gia')),
            ],
            options={
                'verbose_name': 'Vùng',
                'verbose_name_plural': 'Vùng',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('hiragana', models.CharField(max_length=50, verbose_name='Tên tiếng nhật')),
                ('name', models.CharField(max_length=50, verbose_name='Tên theo tiếng anh')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Mã')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kanri.region', verbose_name='Vùng')),
            ],
            options={
                'verbose_name': 'Tỉnh',
                'verbose_name_plural': 'Tỉnh',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FatherAndChurch',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('from_date', models.DateField(auto_now=True, null=True, verbose_name='Từ ngày')),
                ('to_date', models.DateField(auto_now=True, null=True, verbose_name='Đến ngày')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Còn phụ trách')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.church', verbose_name='Nhà thờ')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.father', verbose_name='Cha')),
            ],
            options={
                'verbose_name': 'Cha tại nhà thờ',
                'verbose_name_plural': 'Cha tại nhà thờ',
                'ordering': ('is_active', 'father__full_name', 'church__name'),
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AddField(
            model_name='facility',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.region', verbose_name='Vùng'),
        ),
        migrations.CreateModel(
            name='ChurchImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/church/', verbose_name='Image')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.church')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ảnh nhà thờ',
                'verbose_name_plural': 'Ảnh nhà thờ',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='church',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.region', verbose_name='Vùng'),
        ),
        migrations.AddField(
            model_name='church',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, help_text='Người cuối cập nhật', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
