# Generated by Django 3.2.16 on 2023-01-03 13:02

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='church',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='church',
            name='notice_on_map',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Nội dung hiển thị trên Map', null=True, verbose_name='Thông báo'),
        ),
        migrations.AlterField(
            model_name='church',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Tên', max_length=200, verbose_name='Tên'),
        ),
    ]
