# Generated by Django 3.2.16 on 2023-01-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0002_auto_20230103_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='church',
            name='updated_user',
        ),
        migrations.AlterField(
            model_name='church',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='churchimages',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên nhóm', max_length=120, verbose_name='Tên nhóm')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh đại diện', null=True, upload_to='images/group', verbose_name='Hình ảnh')),
                ('type', models.CharField(choices=[('commu', 'Cộng đoàn'), ('group', 'Nhóm giới trẻ')], default='group', help_text='Cộng đoàn hoặc nhóm giới trẻ', max_length=10, verbose_name='Phân loại')),
                ('introduction', tinymce.models.HTMLField(blank=True, help_text='Mô tả sơ lược về nhóm', verbose_name='Giới thiệu')),
                ('url', models.CharField(blank=True, default='', help_text='Link liên kết facebook', max_length=100, verbose_name='Facebook URL')),
                ('email', models.CharField(blank=True, default='', help_text='Địa chỉ email', max_length=50, null=True, verbose_name='Email')),
                ('address', models.CharField(help_text='Địa chỉ', max_length=400, verbose_name='Địa chỉ sinh hoạt')),
                ('google_map_link', models.CharField(max_length=500, verbose_name='googlemap link')),
                ('notice_on_map', tinymce.models.HTMLField(blank=True, default='', help_text='Nội dung hiển thị trên Map', null=True, verbose_name='Thông báo')),
                ('geo_lon', models.FloatField(blank=True, default=0.0, help_text='Kinh độ theo bản đồ Google', null=True, verbose_name='Kinh độ')),
                ('geo_lat', models.FloatField(blank=True, default=0.0, help_text='Vĩ độ theo bản đồ Google', null=True, verbose_name='Vĩ độ')),
                ('geo_hash', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='geo_hash')),
                ('created_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.church', verbose_name='Nhà thờ sinh hoạt')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.region', verbose_name='Vùng')),
            ],
            options={
                'verbose_name': 'Cộng đoàn, nhóm',
                'verbose_name_plural': 'Cộng đoàn, nhóm',
                'ordering': ['name', 'created_on'],
            },
        ),
    ]
