# Generated by Django 3.2.16 on 2023-01-07 07:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0004_auto_20230107_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='father',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AddField(
            model_name='father',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanri.region', verbose_name='Vùng'),
        ),
        migrations.AlterField(
            model_name='father',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Địa chỉ hiện tại'),
        ),
        migrations.AlterField(
            model_name='father',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link facebook'),
        ),
        migrations.AlterField(
            model_name='father',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Giới thiệu'),
        ),
    ]
