# Generated by Django 3.2.16 on 2023-01-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0005_auto_20230107_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='father',
            name='facility',
        ),
    ]
