# Generated by Django 3.2.16 on 2023-01-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0006_remove_father_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name', 'province', 'created_on'], 'verbose_name': 'Cộng đoàn, nhóm', 'verbose_name_plural': 'Cộng đoàn, nhóm'},
        ),
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Còn hoạt động'),
        ),
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='Slug'),
        ),
    ]
