# Generated by Django 3.2.16 on 2023-01-11 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0007_auto_20230109_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('introduction', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Giới thiệu')),
                ('facebook', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link facebook')),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Địa chỉ hiện tại')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Số điện thoại')),
                ('account_confimred', models.BooleanField(blank=True, default=False, null=True, verbose_name='Xác minh')),
                ('created_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('province', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representatives',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ('created_on',), 'verbose_name': 'Quý cha', 'verbose_name_plural': 'Quý cha'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='region',
        ),
        migrations.RemoveField(
            model_name='father',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='father',
            name='region',
        ),
        migrations.AddField(
            model_name='community',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='father',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='father',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='father',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='father',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='fatherandchurch',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='fatherandchurch',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_and_church_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='fatherandchurch',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='fatherandchurch',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_and_church_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='church',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='churchimages',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_image_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='community',
            name='province',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AlterField(
            model_name='father',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Địa chỉ hiện tại'),
        ),
        migrations.CreateModel(
            name='RepresentativeResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Hoat dong')),
                ('created_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_resp_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_resp_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Representative responsibility',
                'verbose_name_plural': 'Representative responsibilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeAndCommunity',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('from_date', models.DateField(auto_now=True, null=True, verbose_name='Từ ngày')),
                ('to_date', models.DateField(auto_now=True, null=True, verbose_name='Đến ngày')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Còn phụ trách')),
                ('created_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.community', verbose_name='Nhom')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_comm_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.representative', verbose_name='Truong')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanri.representativeresponsibility', verbose_name='Trach nhiem')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_comm_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Communnity and representative',
                'verbose_name_plural': 'Communnity and representatives',
                'ordering': ('is_active', 'community', 'responsibility', 'representative', '-from_date', '-to_date'),
            },
        ),
    ]
