# Generated by Django 3.2.16 on 2023-01-11 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0008_auto_20230111_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name', 'province', 'created_on'], 'verbose_name': 'Master-Group-Cộng đoàn, nhóm', 'verbose_name_plural': 'Master-Group-Cộng đoàn, nhóm'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('english_name',), 'verbose_name': 'Master-Đất nước', 'verbose_name_plural': 'Master-Đất nước'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Master-Facility', 'verbose_name_plural': 'Master-Facilities'},
        ),
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ('created_on',), 'verbose_name': 'Master-User-Quý cha', 'verbose_name_plural': 'Master-User-Quý cha'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('language_name',), 'verbose_name': 'Master-Ngôn ngữ', 'verbose_name_plural': 'Master-Ngôn ngữ'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('name',), 'verbose_name': 'Master-Tỉnh', 'verbose_name_plural': 'Master-Tỉnh'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Master-Vùng', 'verbose_name_plural': 'Master-Vùng'},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ('-created_on',), 'verbose_name': 'Master-User-Representative', 'verbose_name_plural': 'Master-Representatives'},
        ),
        migrations.AlterModelOptions(
            name='representativeandcommunity',
            options={'ordering': ('is_active', 'community', 'responsibility', 'representative', '-from_date', '-to_date'), 'verbose_name': 'Master-Communnity and representative', 'verbose_name_plural': 'Master-Communnity and representatives'},
        ),
        migrations.AlterModelOptions(
            name='representativeresponsibility',
            options={'ordering': ['name'], 'verbose_name': 'Master-Representative responsibility', 'verbose_name_plural': 'Master-Representative responsibilities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='community',
            name='province',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='community_province', to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='father',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='father',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='fatherandchurch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='fatherandchurch',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_and_church_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='representativeandcommunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='representativeandcommunity',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_comm_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='representativeandcommunity',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_comm_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='representativeresponsibility',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='representativeresponsibility',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_resp_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('facebook', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='Link facebook')),
                ('address', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Còn phụ trách')),
                ('account_confimred', models.BooleanField(blank=True, default=False, null=True, verbose_name='Xác minh')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Mã xác nhận')),
                ('code_created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời gian tạo mã')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('community', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_community', to='kanri.community', verbose_name='Cộng đoàn, Nhóm')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_province', to='kanri.province', verbose_name='Tỉnh')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Master-User-User profile',
                'verbose_name_plural': 'Master-User-User profiles',
                'ordering': ('user__username', 'user__email'),
            },
        ),
    ]
