# Generated by Django 3.2.16 on 2023-01-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0011_auto_20230111_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name': '01- Nhà thờ', 'verbose_name_plural': '01- Nhà thờ'},
        ),
        migrations.AlterModelOptions(
            name='churchimages',
            options={'ordering': ['created_on'], 'verbose_name': '01- Nhà thờ ảnh', 'verbose_name_plural': '01- Nhà thờ ảnh'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name', 'province', 'created_on'], 'verbose_name': '20- Cộng đoàn, nhóm', 'verbose_name_plural': '20- Cộng đoàn, nhóm'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': '00- Nhà dòng', 'verbose_name_plural': '00- Nhà dòng'},
        ),
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ('created_on',), 'verbose_name': '10- Quý cha', 'verbose_name_plural': '10- Quý cha'},
        ),
        migrations.AlterModelOptions(
            name='fatherandchurch',
            options={'ordering': ('is_active', 'father', 'church__name'), 'verbose_name': '10- Quý cha tại nhà thờ', 'verbose_name_plural': '10- Quý cha tại nhà thờ'},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ('-created_on',), 'verbose_name': '20-1 Ban đại diện', 'verbose_name_plural': '20-1 Ban đại diện'},
        ),
        migrations.AlterModelOptions(
            name='representativeandcommunity',
            options={'ordering': ('is_active', 'community', 'responsibility', 'representative', '-from_date', '-to_date'), 'verbose_name': '20-2 Ban đại diện nhóm, cộng đoàn', 'verbose_name_plural': '20-2 Ban đại diện nhóm, cộng đoàn'},
        ),
        migrations.AlterModelOptions(
            name='representativeresponsibility',
            options={'ordering': ['name'], 'verbose_name': '20-0 Ban đại diện chức vụ', 'verbose_name_plural': '20-0 Ban đại diện chức vụ'},
        ),
        migrations.AddField(
            model_name='facility',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='facility',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='churchimages',
            name='title',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Mô tả về bức hình'),
        ),
    ]
