# Generated by Django 3.2.16 on 2023-01-15 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanri', '0012_auto_20230115_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('question', models.CharField(max_length=500, verbose_name='Câu hỏi')),
                ('answer', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Câu trả lời')),
                ('is_replied', models.BooleanField(blank=True, default=False, null=True, verbose_name='Trả lời')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_province', to='kanri.province', verbose_name='Tỉnh')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '30-0 Liên lạc hỗ trợ',
                'verbose_name_plural': '30-0 Liên lạc hỗ trợ',
                'ordering': ['-is_replied', 'created_on'],
            },
        ),
    ]
