# Generated by Django 3.2.16 on 2023-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0013_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['is_replied', '-created_on'], 'verbose_name': '30-0 Liên lạc hỗ trợ', 'verbose_name_plural': '30-0 Liên lạc hỗ trợ'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='answer',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Câu trả lời'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='question',
            field=models.TextField(max_length=500, verbose_name='Câu hỏi'),
        ),
    ]
