# Generated by Django 3.2.16 on 2023-01-20 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0014_auto_20230115_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(max_length=100, verbose_name='Trang')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ngày')),
                ('count', models.IntegerField(blank=True, default=1, null=True, verbose_name='Lượt truy cập')),
            ],
            options={
                'verbose_name': '88 Lượng truy cập',
                'verbose_name_plural': '88 Lượng truy cập',
                'ordering': ['-count', '-date', 'page'],
            },
        ),
        migrations.AddField(
            model_name='church',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Còn hoạt động'),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Còn hoạt động'),
        ),
        migrations.AddField(
            model_name='father',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Còn hoạt động'),
        ),
        migrations.AddField(
            model_name='representative',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Còn hoạt động'),
        ),
        migrations.AlterField(
            model_name='church',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_province', to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AlterField(
            model_name='church',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_region', to='kanri.region', verbose_name='Vùng'),
        ),
    ]
