# Generated by Django 3.2.16 on 2023-01-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0015_auto_20230120_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ('-created_on',), 'verbose_name': '10- Quý cha', 'verbose_name_plural': '10- Quý cha'},
        ),
        migrations.AlterField(
            model_name='father',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_province', to='kanri.province', verbose_name='Tỉnh'),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_province', to='kanri.region', verbose_name='Vùng'),
        ),
        migrations.AlterUniqueTogether(
            name='father',
            unique_together=set(),
        ),
    ]
