# Generated by Django 3.2.16 on 2023-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanri', '0017_alter_accesscount_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('sequence',), 'verbose_name': 'Master-Vùng', 'verbose_name_plural': 'Master-Vùng'},
        ),
        migrations.AddField(
            model_name='region',
            name='sequence',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Thứ tự'),
        ),
    ]
