# Generated by Django 3.2.16 on 2023-01-14 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', '-created_on', 'title'], 'verbose_name': '0-Sự kiện', 'verbose_name_plural': '0-Sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='eventboard',
            options={'ordering': ['event', 'title', 'is_active', 'created_on'], 'verbose_name': '5-Các Ban', 'verbose_name_plural': '5-Các Ban'},
        ),
        migrations.AlterModelOptions(
            name='eventboardandmember',
            options={'ordering': ('is_active', 'event_board', 'member', 'member_type'), 'verbose_name': '5-Các Ban-thành viên', 'verbose_name_plural': '5-Các Ban-thành viên'},
        ),
        migrations.AlterModelOptions(
            name='eventboardtask',
            options={'ordering': ['board', 'from_date_time', 'to_date_time', 'status', 'is_active'], 'verbose_name': '5-Các Ban-nhiệm vụ', 'verbose_name_plural': '5-Các Ban-nhiệm vụ'},
        ),
        migrations.AlterModelOptions(
            name='eventgroupscoretype',
            options={'ordering': ['title', 'is_active', 'created_on'], 'verbose_name': '7-Chấm điểm phân loại', 'verbose_name_plural': '7-Chấm điểm phân loại'},
        ),
        migrations.AlterModelOptions(
            name='eventprogramdetail',
            options={'ordering': ['event', 'event_date', '-from_time', 'title'], 'verbose_name': '1-Chương trình', 'verbose_name_plural': '1-Chương trình'},
        ),
        migrations.AlterModelOptions(
            name='eventrulecontent',
            options={'ordering': ['event', 'title', 'sequence', '-created_on'], 'verbose_name': '2-Quy định', 'verbose_name_plural': '2-Quy định'},
        ),
        migrations.AlterModelOptions(
            name='eventtransaction',
            options={'ordering': ['event', 'on_board', 'transaction_amount', 'transaction_type'], 'verbose_name': '8-Giao dịch', 'verbose_name_plural': '8-Giao dịch'},
        ),
        migrations.AlterModelOptions(
            name='eventtransactionaccount',
            options={'ordering': ['title', 'created_on'], 'verbose_name': '8-Giao dịch phân loại', 'verbose_name_plural': '8-Giao dịch phân loại'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['event', '-date_time', 'user'], 'verbose_name': '4-Đăng ký', 'verbose_name_plural': '3-Đăng ký'},
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Câu chủ đề'),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Thời gian kết thúc'),
        ),
    ]
