# Generated by Django 3.2.16 on 2023-01-01 04:46

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='web_images/announ', verbose_name='Image')),
                ('short_introduce', tinymce.models.HTMLField(verbose_name='short introduce')),
                ('content', tinymce.models.HTMLField(verbose_name='Full content')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='Publish')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
            options={
                'verbose_name': 'Giới thiệu',
                'verbose_name_plural': 'Giới thiệu',
                'ordering': ['created_date'],
            },
        ),
    ]
