# Generated by Django 3.2.16 on 2023-01-03 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230103_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gospel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Tiêu đề')),
                ('slug', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Tóm lược')),
            ],
        ),
        migrations.AlterField(
            model_name='massdateschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GospelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(default='', max_length=300, verbose_name='Tiêu đề')),
                ('slug', models.CharField(default='', max_length=400, verbose_name='slug')),
                ('chapter_reference', models.CharField(default='', max_length=300, verbose_name='Nguồn')),
                ('paragraphs', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('gospel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gospel', to='home.gospel', verbose_name='Bài đọc')),
            ],
        ),
        migrations.AddField(
            model_name='massdateschedule',
            name='gospel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mass_gospel', to='home.gospel', verbose_name='Bài đọc'),
            preserve_default=False,
        ),
    ]
