# Generated by Django 3.2.16 on 2023-01-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20230103_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Chủ đề')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='web_images/post', verbose_name='Hình ảnh')),
                ('excerpt', models.CharField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['created_on'], 'verbose_name': 'Giới thiệu', 'verbose_name_plural': 'Giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['priority_choice', 'isActive', 'created_on'], 'verbose_name': 'Thông báo chung', 'verbose_name_plural': 'Thông báo chung'},
        ),
        migrations.AlterModelOptions(
            name='gospel',
            options={'ordering': ['-date'], 'verbose_name': 'Lời Chúa chủ đề', 'verbose_name_plural': 'Lời Chúa chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='gospelcontent',
            options={'ordering': ['gospel', 'sequence'], 'verbose_name': 'Lời Chúa nội dung', 'verbose_name_plural': 'Lời Chúa nội dung'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='created_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='gospelcontent',
            old_name='paragraphs',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='language',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority_choice',
            field=models.CharField(choices=[('3', 'Cao'), ('2', 'Trung bình'), ('1', 'Thấp')], default='2', max_length=10, verbose_name='Ưu tiên'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='audio_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gospel',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='web_images/gospel', verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='sequence',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7')], default='0', max_length=4, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='excerpt',
            field=models.CharField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='web_images/announ', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, verbose_name='Công khai'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announ_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Event date time'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='excerpt',
            field=models.CharField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Công khai từ'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='web_images/announ', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, verbose_name='Công khai'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='register_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Register Link'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Công khai đến'),
        ),
        migrations.AlterField(
            model_name='confessschedule',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='excerpt',
            field=models.CharField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='chapter_reference',
            field=models.CharField(default='', max_length=100, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='gospel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gospel', to='home.gospel', verbose_name='Lời Chúa tiêu đề'),
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Chủ đề')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('excerpt', models.CharField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt')),
                ('youtube_url', models.CharField(max_length=200, verbose_name='Youtube link')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video youtube',
                'verbose_name_plural': 'Video youtube',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='Tên mục')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('sequence', models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7')], default='0', max_length=4, verbose_name='Thứ tự')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='web_images/post', verbose_name='Hình ảnh')),
                ('chapter_summary', models.CharField(help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('edited_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Bài')),
            ],
            options={
                'verbose_name': 'Nội dung bài viết',
                'verbose_name_plural': 'Nội dung bài viết',
                'ordering': ['post', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.posttype', verbose_name='Loại'),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Chủ đề')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='web_images/letter', verbose_name='Hình ảnh')),
                ('excerpt', models.CharField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thư mục vụ',
                'verbose_name_plural': 'Thư mục vụ',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='GospelReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Tiêu đề')),
                ('slug', models.CharField(default='', max_length=400, verbose_name='slug')),
                ('audio_link', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link')),
                ('excerpt', models.CharField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_author', to=settings.AUTH_USER_MODEL)),
                ('gospel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_gospel', to='home.gospel', verbose_name='Lời Chúa tiêu đề')),
            ],
            options={
                'verbose_name': 'Lời Chúa suy niệm',
                'verbose_name_plural': 'Lời Chúa suy niệm',
                'ordering': ['gospel', '-created_on'],
            },
        ),
    ]
