# Generated by Django 3.2.16 on 2023-01-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230105_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='excerpt',
            field=models.TextField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='excerpt',
            field=models.TextField(help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='massdateschedule',
            name='gospel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_gospel', to='home.gospel', verbose_name='Bài đọc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='excerpt',
            field=models.TextField(help_text='Không quá 300 ký tự', max_length=300, verbose_name='Tóm tắt'),
        ),
    ]
