# Generated by Django 3.2.16 on 2023-01-08 12:38

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230107_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GospelRandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='', help_text='Câu lời chúa', max_length=500, verbose_name='Câu nói')),
                ('content', models.TextField(blank=True, default='', help_text='Ý nghĩa câu Lời Chúa', max_length=2000, verbose_name='Nội dung')),
                ('image_vertical', models.CharField(default='', help_text='Link driver, hình cho điện thoại', max_length=200, verbose_name='Hình ảnh dọc')),
                ('image_horizontal', models.CharField(default='', help_text='Link driver hình khổ ngang', max_length=200, verbose_name='Hình ảnh khổ ngang')),
                ('number_downloaded', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đã tải về', null=True, verbose_name='Số lượt tải về')),
                ('status', models.BooleanField(blank=True, default=True, help_text='Trạng thái hoạt động', verbose_name='Trạng thái')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('image_url', models.ImageField(blank=True, help_text='Hình ảnh hiển thị trên trang web', null=True, upload_to='gospel_img', verbose_name='Hình ảnh')),
            ],
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ['name'], 'verbose_name': 'Loại bài viết', 'verbose_name_plural': 'Loại bài viết'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='gospel',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='postcontent',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.ImageField(blank=True, help_text='Hình ảnh phải được xử lý trước khi upload.', null=True, upload_to='web_images/announ', verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='number_listened',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt nghe', null=True, verbose_name='Số lượt nghe'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='number_listened',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt nghe', null=True, verbose_name='Số lượt nghe'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='letter',
            name='audio_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link'),
        ),
        migrations.AddField(
            model_name='letter',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='letter',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='excerpt',
            field=models.TextField(help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='excerpt',
            field=models.TextField(help_text='Không quá 1000 ký tự', max_length=1000, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='excerpt',
            field=models.TextField(help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
    ]
