# Generated by Django 3.2.16 on 2023-01-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230109_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority_choice', 'is_active', '-created_on'], 'verbose_name': 'Thông báo chung', 'verbose_name_plural': 'Thông báo chung'},
        ),
    ]
