# Generated by Django 3.2.16 on 2023-01-11 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_alter_announcement_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterModelOptions(
            name='gospel',
            options={'ordering': ['-date', '-created_on'], 'verbose_name': 'Lời Chúa chủ đề', 'verbose_name_plural': 'Lời Chúa chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='gospelrandom',
            options={'ordering': ['word', 'is_active', '-created_on'], 'verbose_name': 'Câu lời Chúa', 'verbose_name_plural': 'Câu lời Chúa'},
        ),
        migrations.AlterModelOptions(
            name='massdateschedule',
            options={'ordering': ['-date', '-created_on'], 'verbose_name': 'Lịch Lễ', 'verbose_name_plural': 'Lịch Lễ'},
        ),
        migrations.RemoveField(
            model_name='gospelrandom',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='gospelrandom',
            name='status',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='edited_by',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='confessschedule',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confession_time_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='confessschedule',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='confessschedule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='confessschedule',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='confessschedule',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confession_time_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_content_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_content_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_random_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Trạng thái công khai', verbose_name='Công khai'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='number_shared',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_random_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospel_reflection_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='massdateschedule',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='massdateschedule',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_date_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='massdateschedule',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='massdateschedule',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_date_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='masstimeschedule',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='masstimeschedule',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_time_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='masstimeschedule',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='masstimeschedule',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_time_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_content_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_content_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_type_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_type_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_link_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announ_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confessschedule',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_link_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
    ]
