# Generated by Django 3.2.16 on 2023-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230111_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gospelcontent',
            name='sequence',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7'), ('7', '8'), ('8', '9'), ('9', '10'), ('10', '11')], default='0', max_length=4, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='sequence',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7'), ('7', '8'), ('8', '9'), ('9', '10'), ('10', '11')], default='0', max_length=4, verbose_name='Thứ tự'),
        ),
    ]
