# Generated by Django 3.2.16 on 2023-01-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20230114_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['-created_on'], 'verbose_name': '80-Giới thiệu', 'verbose_name_plural': '80-Giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority_choice', 'is_active', '-created_on'], 'verbose_name': '70-Thông báo chung', 'verbose_name_plural': '70-Thông báo chung'},
        ),
        migrations.AlterModelOptions(
            name='confessschedule',
            options={'ordering': ['-from_date_time'], 'verbose_name': '31-Lịch giải tội', 'verbose_name_plural': '31-Lịch giải tội'},
        ),
        migrations.AlterModelOptions(
            name='gospel',
            options={'ordering': ['-date', '-created_on'], 'verbose_name': '11-Lời Chúa-01-chủ đề', 'verbose_name_plural': '11-Lời Chúa-01-chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='gospelcontent',
            options={'ordering': ['gospel', 'sequence', '-created_on'], 'verbose_name': '11-Lời Chúa-02-nội dung', 'verbose_name_plural': '11-Lời Chúa-02-nội dung'},
        ),
        migrations.AlterModelOptions(
            name='gospelrandom',
            options={'ordering': ['word', 'is_active', '-created_on'], 'verbose_name': '10-Câu lời Chúa', 'verbose_name_plural': '10-Câu lời Chúa'},
        ),
        migrations.AlterModelOptions(
            name='gospelreflection',
            options={'ordering': ['gospel', '-created_on'], 'verbose_name': '11-Lời Chúa-04-suy niệm', 'verbose_name_plural': '11-Lời Chúa-04-suy niệm'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_on'], 'verbose_name': '20-Giáo lý-02 chủ đề', 'verbose_name_plural': '20-Giáo lý-02 chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='lessonchapter',
            options={'ordering': ['lesson', 'sequence', '-created_on'], 'verbose_name': '20-Giáo lý-03 chương', 'verbose_name_plural': '20-Giáo lý-03 chương'},
        ),
        migrations.AlterModelOptions(
            name='lessonchapterqa',
            options={'ordering': ['chapter', 'question_no', '-created_on'], 'verbose_name': '20-Giáo lý-03 chương câu hỏi', 'verbose_name_plural': '20-Giáo lý-03 chương câu hỏi'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'ordering': ['name'], 'verbose_name': '20-Giáo lý-01 phân loại', 'verbose_name_plural': '20-Giáo lý-01 phân loại'},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['created_on'], 'verbose_name': '01-Thư mục vụ', 'verbose_name_plural': '01-Thư mục vụ'},
        ),
        migrations.AlterModelOptions(
            name='massdateschedule',
            options={'ordering': ['-date', '-created_on'], 'verbose_name': '30-Lịch Lễ-01 ngày', 'verbose_name_plural': '30-Lịch Lễ-01 ngày'},
        ),
        migrations.AlterModelOptions(
            name='masstimeschedule',
            options={'ordering': ['-date_schedule'], 'verbose_name': '30-Lịch Lễ-02 giờ chi tiết', 'verbose_name_plural': '30-Lịch Lễ-02 giờ chi tiết'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': '02-Bài viết-02-chủ đề', 'verbose_name_plural': '02-Bài viết-02-chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='postcontent',
            options={'ordering': ['post', 'sequence', '-created_on'], 'verbose_name': '02-Bài viết-03-nội dung', 'verbose_name_plural': '02-Bài viết-03-nội dung'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ['name'], 'verbose_name': '02-Bài viết-01-phân loại', 'verbose_name_plural': '02-Bài viết-01-phân loại'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['created_on', 'title'], 'verbose_name': '99-Youtube video', 'verbose_name_plural': '99-Youtube videos'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lessontype',
            name='language',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_jp',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Anh'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='excerpt_jp',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Anh'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='audio_link_en',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='audio_link_jp',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='excerpt_jp',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='title_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='chapter_reference_en',
            field=models.CharField(default='', max_length=100, verbose_name='Tác giả tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='chapter_reference_jp',
            field=models.CharField(default='', max_length=100, verbose_name='Tác giả tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='chapter_title_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tiêu đề tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='chapter_title_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tiêu đề tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelcontent',
            name='content_jp',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='audio_link_en',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='audio_link_jp',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='content_jp',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='excerpt_jp',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='reference_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Anh'),
        ),
        migrations.AddField(
            model_name='gospelreflection',
            name='title_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_no',
            field=models.SmallIntegerField(default=0, verbose_name='Bài số'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Anh'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Chủ đề tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='lessonchapter',
            name='chapter_no',
            field=models.SmallIntegerField(default=0, verbose_name='Chương số'),
        ),
        migrations.AddField(
            model_name='lessonchapterqa',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='lessonchapterqa',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_chapter_qa_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonchapterqa',
            name='number_readed',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='lessonchapterqa',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='lessonchapterqa',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_chapter_qa_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='masstimeschedule',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='slug',
            field=models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='confessschedule',
            name='slug',
            field=models.CharField(default='', help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='slug',
            field=models.CharField(default='', help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gospel',
            name='title',
            field=models.CharField(default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='chapter_title',
            field=models.CharField(default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='slug',
            field=models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='excerpt',
            field=models.TextField(default='', help_text='Không quá 500 ký tự', max_length=500, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='gospel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_gospel', to='home.gospel', verbose_name='Lời Chúa'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='slug',
            field=models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='title',
            field=models.CharField(default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Không quá 500 ký tự', max_length=500, null=True, verbose_name='Tóm tắt tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessontype', verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='lessonchapter',
            name='chapter_title',
            field=models.CharField(help_text='Dài không quá 200 ký tự', max_length=200, verbose_name='Tên chương'),
        ),
        migrations.AlterField(
            model_name='lessonchapter',
            name='slug',
            field=models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='lessonchapterqa',
            name='answer',
            field=models.TextField(help_text='Dài không quá 2000 ký tự', max_length=2000, verbose_name='Câu trả lời'),
        ),
        migrations.AlterField(
            model_name='lessonchapterqa',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessonchapter', verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='lessonchapterqa',
            name='question',
            field=models.TextField(help_text='Dài không quá 1000 ký tự', max_length=1000, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='slug',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='slug',
            field=models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='massdateschedule',
            name='slug',
            field=models.CharField(default='', help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='chapter_title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tên mục'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='slug',
            field=models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='name',
            field=models.CharField(help_text='Dài không quá 200 ký tự', max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='slug',
            field=models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề'),
        ),
        migrations.CreateModel(
            name='PrayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dài không quá 200 ký tự', max_length=200, verbose_name='Tên')),
                ('name_jp', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Nhật')),
                ('name_en', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Anh')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_type_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_type_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '25-Kinh đọc-01-phân loại',
                'verbose_name_plural': '02-Kinh đọc-01-phân loại',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tên')),
                ('name_jp', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Nhật')),
                ('name_en', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Anh')),
                ('slug', models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug')),
                ('audio_link', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link')),
                ('audio_link_jp', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật')),
                ('audio_link_en', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('content_jp', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật')),
                ('content_en', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh')),
                ('reference_link', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Nguồn tham khảo Link')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('number_readed', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc')),
                ('number_shared', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.posttype', verbose_name='Loại')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '25-Kinh đọc-02 nội dung',
                'verbose_name_plural': '25-Kinh đọc-02 nội dung',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LessonQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.SmallIntegerField(default=0, verbose_name='Câu hỏi số')),
                ('question', models.TextField(help_text='Dài không quá 1000 ký tự', max_length=1000, verbose_name='Câu hỏi')),
                ('answer_1', models.TextField(help_text='Dài không quá 1000 ký tự', max_length=1000, verbose_name='Đáp án A')),
                ('answer_2', models.TextField(blank=True, default='', help_text='Dài không quá 1000 ký tự', max_length=1000, null=True, verbose_name='Đáp án B')),
                ('answer_3', models.TextField(blank=True, default='', help_text='Dài không quá 1000 ký tự', max_length=1000, null=True, verbose_name='Đáp án C')),
                ('answer_4', models.TextField(blank=True, default='', help_text='Dài không quá 1000 ký tự', max_length=1000, null=True, verbose_name='Đáp án D')),
                ('correct_answer', models.TextField(default='A', max_length=2, verbose_name='Câu trả lời đúng')),
                ('number_answered', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Số lượt làm')),
                ('number_correct', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Số lượt làm đúng')),
                ('number_readed', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc')),
                ('number_shared', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_qa_created_user', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lesson', verbose_name='Bài')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_qa_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '20-Giáo lý-03 chương câu hỏi',
                'verbose_name_plural': '20-Giáo lý-03 chương câu hỏi',
                'ordering': ['lesson', 'question_no', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CommuintyPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tiêu đề')),
                ('title_jp', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tiêu đề tiếng Nhật')),
                ('title_en', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tiêu đề tiếng Anh')),
                ('slug', models.CharField(help_text='Vui lòng chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('content_jp', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật')),
                ('content_en', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh')),
                ('reference_link', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Nguồn tham khảo Link')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_prayer_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('gospel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gospel_community_prayer', to='home.gospel', verbose_name='Lời Chúa')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_prayer_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '11-Lời Chúa-03- Lời nguyện giáo dân',
                'verbose_name_plural': '11-Lời Chúa-03- Lời nguyện giáo dân',
                'ordering': ['gospel', 'title', '-created_on'],
            },
        ),
    ]
