# Generated by Django 3.2.16 on 2023-01-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20230114_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confessschedule',
            options={'ordering': ['-from_date_time'], 'verbose_name': '41-Lịch giải tội', 'verbose_name_plural': '41-Lịch giải tội'},
        ),
        migrations.AlterModelOptions(
            name='gospel',
            options={'ordering': ['-date', 'year_type', '-created_on'], 'verbose_name': '11-Lời Chúa-01-chủ đề', 'verbose_name_plural': '11-Lời Chúa-01-chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_type', 'lesson_no', '-created_on'], 'verbose_name': '20-Giáo lý-02 chủ đề', 'verbose_name_plural': '20-Giáo lý-02 chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='lessonchapterqa',
            options={'ordering': ['chapter', 'question_no', '-created_on'], 'verbose_name': '20-Giáo lý-04 chương câu hỏi', 'verbose_name_plural': '20-Giáo lý-04 chương câu hỏi'},
        ),
        migrations.AlterModelOptions(
            name='lessonqa',
            options={'ordering': ['lesson', 'question_no', '-created_on'], 'verbose_name': '20-Giáo lý-04 Bài câu hỏi', 'verbose_name_plural': '20-Giáo lý-04 Bài câu hỏi'},
        ),
        migrations.AlterModelOptions(
            name='massdateschedule',
            options={'ordering': ['-date', '-created_on'], 'verbose_name': '40-Lịch Lễ-01 ngày', 'verbose_name_plural': '40-Lịch Lễ-01 ngày'},
        ),
        migrations.AlterModelOptions(
            name='masstimeschedule',
            options={'ordering': ['-date_schedule'], 'verbose_name': '40-Lịch Lễ-02 giờ chi tiết', 'verbose_name_plural': '40-Lịch Lễ-02 giờ chi tiết'},
        ),
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['prayer_type', 'name', '-created_on'], 'verbose_name': '25-Kinh đọc-02 nội dung', 'verbose_name_plural': '25-Kinh đọc-02 nội dung'},
        ),
        migrations.AlterModelOptions(
            name='prayertype',
            options={'ordering': ['name'], 'verbose_name': '25-Kinh đọc-01-phân loại', 'verbose_name_plural': '25-Kinh đọc-01-phân loại'},
        ),
        migrations.RemoveField(
            model_name='gospel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='post_type',
        ),
        migrations.AddField(
            model_name='gospel',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AddField(
            model_name='gospel',
            name='year_type',
            field=models.CharField(choices=[('A', 'Năm A'), ('B', 'Năm B'), ('C', 'Năm C')], default='A', max_length=2, verbose_name='Năm phụng vụ'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AddField(
            model_name='lessonqa',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Công khai'),
        ),
        migrations.AddField(
            model_name='post',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.prayertype', verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='commuintyprayer',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='chapter_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='chapter_reference_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Tác giả tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='gospelcontent',
            name='chapter_reference_jp',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Tác giả tiếng Nhật'),
        ),
        migrations.AlterField(
            model_name='gospelreflection',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Chủ đề tên bài'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='reference_link',
            field=models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link'),
        ),
        migrations.CreateModel(
            name='CeremonyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tên')),
                ('name_jp', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Nhật')),
                ('name_en', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Anh')),
                ('slug', models.CharField(max_length=300, verbose_name='Slug')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremony_type_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremony_type_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '30-Nghi thức-01 phân loại',
                'verbose_name_plural': '30-Nghi thức-01 phân loại',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Tên')),
                ('name_jp', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Nhật')),
                ('name_en', models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, null=True, verbose_name='Tên tiếng Anh')),
                ('slug', models.CharField(help_text='Chỉnh lại phần tự sinh ra cho giống với title, * không dấu', max_length=300, verbose_name='Slug')),
                ('audio_link', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link')),
                ('audio_link_jp', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật')),
                ('audio_link_en', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Audio Link tiếng Nhật')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('content_jp', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Nhật')),
                ('content_en', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Nội dung tiếng Anh')),
                ('reference_link', models.CharField(blank=True, default='', help_text='Nếu có nhiều nguồn vui lòng thêm dấu ";" để phân cách các nguồn tham khảo.', max_length=5000, null=True, verbose_name='Nguồn tham khảo Link')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Công khai')),
                ('number_readed', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt đọc', null=True, verbose_name='Số lượt đọc')),
                ('number_shared', models.SmallIntegerField(blank=True, default=0, help_text='Số lượt chia sẻ', null=True, verbose_name='Số lượt chia sẻ')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremony_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.ceremonytype', verbose_name='Loại')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremony_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': '30-Nghi thức-02 nội dung',
                'verbose_name_plural': '30-Nghi thức-02 nội dung',
                'ordering': ['type', 'name', '-created_on'],
            },
        ),
    ]
