# Generated by Django 3.2.16 on 2023-01-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230115_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masstimeschedule',
            name='date_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_schedule', to='home.massdateschedule', verbose_name='Thánh Lễ'),
        ),
    ]
