# Generated by Django 3.2.16 on 2023-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_masstimeschedule_date_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gospelrandom',
            name='language',
        ),
        migrations.RemoveField(
            model_name='gospelrandom',
            name='number_readed',
        ),
        migrations.RemoveField(
            model_name='gospelrandom',
            name='number_shared',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='type',
            field=models.CharField(choices=[('community', 'Giáo đoàn'), ('father-community', 'Cha tuyên uý'), ('father-youth', 'Cha đặc trách giới trẻ')], default='vcj', help_text='Phân loại chủ đề', max_length=300, verbose_name='Phân loại'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='word_en',
            field=models.TextField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói English'),
        ),
        migrations.AddField(
            model_name='gospelrandom',
            name='word_jp',
            field=models.TextField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói Japanese'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='image_horizontal',
            field=models.CharField(blank=True, default='', help_text='Link driver hình khổ ngang', max_length=400, null=True, verbose_name='Hình ảnh khổ ngang'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='image_url',
            field=models.ImageField(blank=True, help_text='Hình ảnh hiển thị trên trang web', null=True, upload_to='web_images/gospel_img', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='image_vertical',
            field=models.CharField(blank=True, default='', help_text='Link driver, hình cho điện thoại', max_length=400, null=True, verbose_name='Hình ảnh dọc'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='word',
            field=models.TextField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói'),
        ),
    ]
