# Generated by Django 3.2.16 on 2023-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230117_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gospelrandom',
            name='image_horizontal',
            field=models.CharField(blank=True, default='', help_text='Link drive, hình cover facebook', max_length=400, null=True, verbose_name='Hình ảnh khổ ngang'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='image_vertical',
            field=models.CharField(blank=True, default='', help_text='Link drive, hình nền cho điện thoại', max_length=400, null=True, verbose_name='Hình ảnh dọc'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='word',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='word_en',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói English'),
        ),
        migrations.AlterField(
            model_name='gospelrandom',
            name='word_jp',
            field=models.CharField(blank=True, default='', help_text='Dài không quá 300 ký tự', max_length=300, verbose_name='Câu nói Japanese'),
        ),
    ]
