# Generated by Django 3.2.16 on 2023-01-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230119_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_type_prayer', to='home.prayertype', verbose_name='Loại'),
        ),
    ]
