# Generated by Django 3.2.16 on 2023-01-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ceremony_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masstimeschedule',
            options={'ordering': ['date_schedule', '-time'], 'verbose_name': '40-Lịch Lễ-02 giờ chi tiết', 'verbose_name_plural': '40-Lịch Lễ-02 giờ chi tiết'},
        ),
    ]
