# Generated by Django 3.2.16 on 2023-01-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_masstimeschedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masstimeschedule',
            options={'ordering': ['date_schedule', 'time'], 'verbose_name': '40-Lịch Lễ-02 giờ chi tiết', 'verbose_name_plural': '40-Lịch Lễ-02 giờ chi tiết'},
        ),
    ]
